In [1]:
import hces
import pandas as pd
df = hces.load()
df.head()

,sector,nss_region,multiplier,family_size,n_children,n_schoolchildren,n_elderly,n_school_meals,employed_annual,nco_2015,...,used_ration_card,procured_rice,procured_wheat,procured_grain,procured_sugar,procured_pulses,procured_edible_oil,procured_other,performed_ceremony,meals_served_to_nonhh
hhid,,,,,,,,,,,,,,,,,,,,,
46667201,rural,12,16669,5,0,0,0,0.0,yes,112.0,...,yes,True,True,False,False,False,False,False,no,8
46667301,rural,12,24840,4,0,0,0,0.0,yes,233.0,...,no,False,False,False,False,False,False,False,no,16
46667302,rural,12,24840,5,3,3,0,0.0,yes,832.0,...,yes,True,True,False,False,False,False,False,no,30
46667303,rural,12,24840,5,1,1,1,0.0,yes,741.0,...,yes,True,True,False,False,False,False,False,no,20
46667304,rural,12,24840,3,0,0,2,0.0,no,NaN,...,no,False,False,False,False,False,False,False,no,18

## PMGKY

In [2]:
df['treat'] = (df['has_benefited_from_pmgky'] == 'yes').astype(int)

In [3]:
xdf = hces.propensity_score_match(df, num_cols=['family_size', 'n_children', 'n_elderly'],                                  
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [5]:
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits    meat  \
           label
values     A      -190.00    4.00       -9.00 -675.00   5.00 -150.00  239.00
           B      -274.00  -27.00      -18.00 -573.00 -72.00 -127.00   67.00
           C      -213.00   -6.00       -9.00 -355.00 -24.00  -50.00   -2.00
           D      -194.00   10.00      -11.00 -345.00   5.00  -24.00   14.00
           E      -136.00   16.00        5.00 -175.00  52.00   -3.00   -1.00
percentage A        -0.19    0.01       -0.06   -0.28   0.00   -0.20    0.34
           B        -0.23   -0.07       -0.10   -0.25  -0.06   -0.17    0.07
           C        -0.19   -0.01       -0.05   -0.19  -0.02   -0.08   -0.00
           D        -0.19    0.03       -0.06   -0.18   0.00   -0.05    0.02
           E        -0.12    0.04        0.03   -0.11   0.04   -0.01   -0.00

                    oil  spice     bev  cooked  processed
           label
values     A       2.00   8.00 -197.00 -533.00    -256.00
           B     -51.00 -30.00 -174.00 -306.00    -193.00
           C     -21.00 -29.00  -76.00 -126.00     -68.00
           D       2.00 -17.00  -43.00  -15.00     -45.00
           E      18.00 -16.00  -41.00  -62.00      -3.00
percentage A       0.00   0.01   -0.25   -0.35      -0.27
           B      -0.09  -0.04   -0.23   -0.24      -0.21
           C      -0.04  -0.04   -0.13   -0.13      -0.10
           D       0.00  -0.03   -0.10   -0.02      -0.08
           E       0.03  -0.02   -0.08   -0.07      -0.01

In [12]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery   fees  coaching  edu_other
           label
values     A          -2.00      -0.00       -2.00  24.00      6.00      -7.00
           B         -17.00      -2.00      -10.00 -31.00    -19.00      -6.00
           C         -10.00      -1.00       -4.00 -36.00     -1.00      -2.00
           D          -3.00      -0.00        3.00 -24.00      3.00      -1.00
           E          -0.00      -2.00        5.00 -29.00     -4.00      -0.00
percentage A          -0.02      -0.06       -0.03   0.08      0.04      -0.24
           B          -0.12      -0.33       -0.13  -0.09     -0.15      -0.25
           C          -0.10      -0.27       -0.07  -0.12     -0.01      -0.13
           D          -0.04      -0.12        0.06  -0.10      0.03      -0.07
           E          -0.00      -0.43        0.09  -0.11     -0.05      -0.02

In [14]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.HEALTH_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                    410   411   412   413   414   420   421   422   423   424
           label
values     A      11.00 -0.00 -1.00  0.00  4.00 -3.00  1.00 -3.00 -0.00 -0.00
           B       4.00 -2.00 -8.00 -4.00 -0.00 -7.00 -0.00 -3.00  0.00 -1.00
           C       1.00 -1.00 -2.00 -4.00 -3.00 -5.00  0.00 -1.00 -0.00 -0.00
           D      -1.00 -1.00 -0.00 -1.00 -3.00 -4.00  0.00 -1.00 -0.00 -0.00
           E      10.00  4.00  3.00  4.00  1.00 -0.00  0.00 -1.00 -0.00  0.00
percentage A       0.15 -0.00 -0.01  0.01  0.18 -0.04  0.11 -0.22 -0.07 -0.10
           B       0.04 -0.03 -0.13 -0.05 -0.02 -0.11 -0.03 -0.22  0.03 -0.33
           C       0.02 -0.02 -0.04 -0.06 -0.12 -0.08  0.04 -0.11 -0.02 -0.22
           D      -0.01 -0.03 -0.00 -0.02 -0.14 -0.08  0.03 -0.12 -0.07 -0.15
           E       0.11  0.09  0.07  0.06  0.05 -0.00  0.08 -0.07 -0.12  0.06

## Ration Card

In [18]:
df['treat'] = (df['used_ration_card'] == 'yes').astype(int)

In [19]:
xdf = hces.propensity_score_match(df, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [21]:
xdf[hces.FOOD_COLS] /= xdf['family_size'].values.reshape(-1, 1)
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits   meat  \
           label
values     A      -104.00   -7.00       -6.00 -258.00 -32.00  -73.00  74.00
           B      -113.00   -8.00       -6.00 -157.00 -15.00  -38.00  53.00
           C      -113.00   -6.00       -6.00 -148.00  -9.00  -18.00  49.00
           D      -105.00   -1.00       -6.00 -104.00   9.00   -0.00  57.00
           E       -96.00   -0.00       -6.00  -82.00   8.00    1.00  40.00
percentage A        -0.32   -0.06       -0.12   -0.34  -0.09   -0.29   0.37
           B        -0.34   -0.08       -0.13   -0.26  -0.05   -0.19   0.24
           C        -0.35   -0.06       -0.14   -0.28  -0.03   -0.12   0.26
           D        -0.34   -0.01       -0.14   -0.25   0.03   -0.00   0.30
           E        -0.32   -0.00       -0.16   -0.25   0.03    0.00   0.19

                    oil  spice     bev  cooked  processed
           label
values     A     -10.00 -14.00 -118.00 -449.00    -107.00
           B     -16.00  -9.00  -53.00 -196.00     -46.00
           C     -15.00  -6.00  -31.00 -119.00     -23.00
           D      -5.00   3.00   -5.00  -18.00     -10.00
           E     -11.00   5.00   -3.00   10.00      -3.00
percentage A      -0.07  -0.08   -0.41   -0.62      -0.34
           B      -0.11  -0.05   -0.26   -0.45      -0.20
           C      -0.11  -0.04   -0.21   -0.37      -0.13
           D      -0.04   0.02   -0.04   -0.09      -0.07
           E      -0.09   0.03   -0.03    0.06      -0.02

In [23]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery   fees  coaching  edu_other
           label
values     A          -6.00       1.00       -4.00  37.00     16.00      -7.00
           B         -20.00      -1.00      -11.00 -36.00     -5.00      -9.00
           C         -13.00       0.00       -7.00 -54.00     12.00      -2.00
           D         -19.00       0.00      -12.00 -64.00      4.00      -7.00
           E         -27.00      -1.00       -9.00 -67.00      0.00      -3.00
percentage A          -0.05       0.13       -0.06   0.11      0.12      -0.26
           B          -0.15      -0.13       -0.15  -0.10     -0.04      -0.33
           C          -0.12       0.08       -0.11  -0.17      0.13      -0.13
           D          -0.19       0.04       -0.17  -0.23      0.05      -0.37
           E          -0.26      -0.25       -0.13  -0.24      0.00      -0.20

In [24]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.HEALTH_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                    410    411    412    413    414   420   421   422   423  \
           label
values     A      10.00   1.00  -2.00   1.00   2.00  1.00  1.00 -1.00  0.00
           B       0.00  -4.00  -7.00  -8.00  -1.00 -2.00  0.00 -2.00 -0.00
           C     -10.00  -6.00 -10.00 -11.00  -4.00 -3.00  1.00 -1.00 -0.00
           D     -13.00  -6.00  -4.00 -11.00  -2.00 -6.00 -1.00 -1.00 -0.00
           E     -25.00 -11.00 -13.00 -13.00 -11.00 -6.00  1.00 -1.00 -1.00
percentage A       0.14   0.02  -0.03   0.02   0.13  0.01  0.13 -0.09  0.25
           B       0.00  -0.07  -0.11  -0.10  -0.03 -0.03  0.02 -0.14 -0.30
           C      -0.10  -0.11  -0.18  -0.15  -0.16 -0.05  0.18 -0.09 -0.34
           D      -0.13  -0.13  -0.09  -0.16  -0.12 -0.10 -0.20 -0.14 -0.21
           E      -0.21  -0.19  -0.21  -0.17  -0.37 -0.11  0.11 -0.10 -0.67

                   424
           label
values     A     -0.00
           B     -1.00
           C     -0.00
           D     -0.00
           E     -1.00
percentage A     -0.12
           B     -0.26
           C     -0.17
           D     -0.10
           E     -0.31

## Someone in the HH hospitalized, received health benefits

In [25]:
edf = df[df['is_hospitalization'] != 4].copy()
edf['treat'] = (edf['is_benefit_healthscheme'] == 1).astype(int)

In [28]:
xdf = hces.propensity_score_match(edf, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [29]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits    meat  \
           label
values     A      -176.00  -36.00      -13.00 -289.00 -58.00 -108.00  -23.00
           B      -107.00  -23.00      -16.00  -57.00  41.00  -50.00   -7.00
           C      -130.00  -45.00       -6.00 -150.00 -68.00  -39.00  -95.00
           D        16.00  -67.00       20.00  263.00 -50.00  -29.00 -123.00
           E         4.00  -72.00       18.00  285.00 -65.00  -60.00 -116.00
percentage A        -0.15   -0.08       -0.08   -0.16  -0.05   -0.12   -0.02
           B        -0.09   -0.05       -0.09   -0.03   0.03   -0.07   -0.01
           C        -0.11   -0.10       -0.03   -0.08  -0.05   -0.06   -0.09
           D         0.01   -0.16        0.11    0.12  -0.04   -0.05   -0.12
           E         0.00   -0.17        0.08    0.11  -0.05   -0.10   -0.14

                    oil  spice    bev  cooked  processed
           label
values     A     -48.00 -66.00 -57.00  -35.00    -125.00
           B      -3.00 -35.00 -65.00  -25.00      -7.00
           C     -52.00 -47.00 -96.00 -119.00    -111.00
           D     -52.00  -2.00   9.00   22.00    -124.00
           E     -77.00   2.00  32.00  148.00     -25.00
percentage A      -0.09  -0.09  -0.07   -0.03      -0.13
           B      -0.01  -0.05  -0.10   -0.02      -0.01
           C      -0.09  -0.07  -0.16   -0.13      -0.13
           D      -0.09  -0.00   0.02    0.03      -0.15
           E      -0.13   0.00   0.05    0.18      -0.03

In [32]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.HEALTH_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                    410     411    412    413    414    420   421   422   423  \
           label
values     A      -0.00   75.00  79.00 -20.00  29.00  14.00  4.00  0.00 -0.00
           B       5.00   38.00  45.00  -1.00  49.00  21.00  0.00  0.00  0.00
           C      39.00  110.00  54.00  42.00  76.00  11.00  8.00  2.00 -0.00
           D     -57.00   97.00   3.00   7.00  82.00  18.00  5.00  1.00 -0.00
           E     -36.00   40.00 -46.00 -37.00  72.00  -2.00  4.00 -1.00  0.00
percentage A      -0.00    0.21   0.19  -0.04   0.22   0.17  0.35  0.00 -0.75
           B       0.01    0.12   0.12  -0.00   0.37   0.25  0.04  0.02  0.91
           C       0.07    0.41   0.20   0.11   0.64   0.13  0.90  0.15 -0.28
           D      -0.11    0.40   0.01   0.02   0.80   0.21  0.54  0.04 -0.44
           E      -0.06    0.16  -0.19  -0.11   0.66  -0.02  0.43 -0.08  0.58

                   424
           label
values     A     -0.00
           B      1.00
           C      0.00
           D      2.00
           E      0.00
percentage A     -0.07
           B      0.26
           C      0.12
           D      0.80
           E      0.07

In [33]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery   fees  coaching  edu_other
           label
values     A         -37.00       1.00      -13.00 -35.00    -34.00      -7.00
           B         -17.00      -1.00       -9.00  -5.00    -20.00      -5.00
           C         -21.00      -0.00       -6.00 -41.00      9.00       4.00
           D         -24.00       0.00        5.00 -26.00    -57.00      11.00
           E          -5.00       1.00       20.00   3.00    -77.00       7.00
percentage A          -0.26       0.22       -0.18  -0.10     -0.41      -0.25
           B          -0.18      -0.26       -0.15  -0.02     -0.24      -0.30
           C          -0.22      -0.09       -0.09  -0.15      0.06       0.26
           D          -0.22       0.07        0.09  -0.10     -0.35       0.80
           E          -0.05       0.32        0.32   0.01     -0.60       0.50

## Nobody got hospitalized, but household insured (Safety net?)

In [34]:
edf = df[df['is_hospitalization'] == 4].copy()
edf['treat'] = (edf['is_hhmem_pmjay'] == 1).astype(int)

In [35]:
xdf = hces.propensity_score_match(edf, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [41]:
xdf[hces.FOOD_COLS] /= xdf['family_size'].values.reshape(-1, 1)
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits   meat  \
           label
values     A       -21.00   -8.00       -2.00 -115.00 -13.00  -42.00  22.00
           B       -17.00  -13.00       -4.00 -116.00 -11.00  -33.00  45.00
           C        -9.00   -7.00       -2.00  -46.00   3.00  -11.00  15.00
           D        -4.00   -4.00       -2.00  -53.00  13.00   -1.00  35.00
           E       -10.00  -15.00       -6.00  -95.00   2.00  -10.00  30.00
percentage A        -0.07   -0.08       -0.05   -0.20  -0.04   -0.20   0.10
           B        -0.06   -0.12       -0.09   -0.22  -0.03   -0.17   0.18
           C        -0.04   -0.07       -0.04   -0.11   0.01   -0.08   0.07
           D        -0.02   -0.04       -0.05   -0.14   0.05   -0.01   0.16
           E        -0.04   -0.15       -0.15   -0.27   0.01   -0.08   0.13

                   oil  spice    bev  cooked  processed
           label
values     A     -6.00 -11.00 -67.00 -233.00     -68.00
           B     -7.00 -11.00 -51.00 -173.00     -58.00
           C     -7.00  -4.00 -11.00  -29.00     -18.00
           D     -2.00   1.00  -8.00  -11.00     -16.00
           E     -4.00 -10.00 -18.00  -11.00     -15.00
percentage A     -0.05  -0.07  -0.28   -0.43      -0.26
           B     -0.05  -0.06  -0.26   -0.39      -0.25
           C     -0.05  -0.03  -0.09   -0.11      -0.11
           D     -0.02   0.01  -0.06   -0.05      -0.11
           E     -0.03  -0.06  -0.16   -0.06      -0.11

In [44]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery   fees  coaching  edu_other
           label
values     A         -17.00      -1.00        8.00  21.00      3.00       0.00
           B         -27.00      -1.00       -3.00 -10.00     39.00      -6.00
           C         -22.00      -1.00        3.00 -35.00      8.00      -2.00
           D         -18.00      -0.00       -2.00 -47.00     37.00      -1.00
           E         -15.00      -1.00       -1.00 -58.00     33.00      -2.00
percentage A          -0.11      -0.25        0.10   0.05      0.02       0.01
           B          -0.21      -0.24       -0.05  -0.03      0.35      -0.25
           C          -0.19      -0.30        0.05  -0.12      0.08      -0.14
           D          -0.20      -0.13       -0.03  -0.19      0.49      -0.09
           E          -0.24      -0.39       -0.02  -0.32      0.55      -0.17

In [40]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.HEALTH_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  410  411  412  413  414   420   421   422   423   424
           label
values     A      0.0  0.0  0.0  0.0  0.0  1.00  2.00 -2.00 -0.00 -1.00
           B      0.0  0.0  0.0  0.0  0.0  2.00  1.00 -2.00  0.00 -0.00
           C      0.0  0.0  0.0  0.0  0.0  0.00  2.00 -1.00 -0.00 -0.00
           D      0.0  0.0  0.0  0.0  0.0  1.00  1.00 -1.00 -0.00 -1.00
           E      0.0  0.0  0.0  0.0  0.0 -1.00  0.00 -1.00  0.00 -1.00
percentage A      NaN  NaN  NaN  NaN  NaN  0.03  0.27 -0.16 -0.02 -0.32
           B      NaN  NaN  NaN  NaN  NaN  0.03  0.15 -0.19  0.01 -0.17
           C      NaN  NaN  NaN  NaN  NaN  0.01  0.34 -0.17 -0.05 -0.11
           D      NaN  NaN  NaN  NaN  NaN  0.02  0.15 -0.13 -0.26 -0.33
           E      NaN  NaN  NaN  NaN  NaN -0.03  0.04 -0.09  0.08 -0.54

## Eligibility - School / college going HH member; Treatment: received fee waiver

In [45]:
edf = df[df['is_hhmem_edu'] == 1].copy()
edf['treat'] = (edf['received_fee_waiver'] == 1).astype(int)

In [46]:
xdf = hces.propensity_score_match(edf, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [54]:
xdf['treat'] = xdf['treat'].astype(int)
xdf[hces.FOOD_COLS] /= xdf['family_size'].values.reshape(-1, 1)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits    meat  \
           label
values     A      -140.00  -45.00       -4.00 -444.00 -87.00 -195.00 -103.00
           B       -71.00  -49.00       -6.00 -328.00 -44.00 -113.00  -29.00
           C       -49.00  -72.00        5.00 -209.00 -82.00 -104.00 -139.00
           D       -14.00  -61.00       11.00    9.00 -73.00  -89.00 -175.00
           E       -52.00  -39.00       13.00   70.00 -50.00  -71.00 -146.00
percentage A        -0.11   -0.10       -0.02   -0.17  -0.07   -0.22   -0.10
           B        -0.06   -0.11       -0.03   -0.15  -0.03   -0.15   -0.02
           C        -0.04   -0.16        0.03   -0.10  -0.06   -0.16   -0.14
           D        -0.01   -0.14        0.06    0.00  -0.06   -0.15   -0.17
           E        -0.05   -0.09        0.07    0.05  -0.04   -0.13   -0.12

                   oil  spice     bev  cooked  processed
           label
values     A     -1.00 -79.00 -194.00 -134.00    -226.00
           B      3.00  -7.00 -153.00 -111.00    -158.00
           C      4.00 -20.00  -75.00   35.00     -81.00
           D     -1.00  -8.00  -37.00   90.00     -57.00
           E     -9.00  -9.00  -31.00  -31.00     -18.00
percentage A     -0.00  -0.11   -0.23   -0.10      -0.21
           B      0.01  -0.01   -0.20   -0.09      -0.17
           C      0.01  -0.03   -0.13    0.04      -0.11
           D     -0.00  -0.01   -0.07    0.10      -0.08
           E     -0.01  -0.01   -0.06   -0.03      -0.03

In [51]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery    fees  coaching  \
           label
values     A         -67.00      -1.00      -13.00 -204.00     22.00
           B         -50.00      -1.00       -4.00 -174.00     35.00
           C         -64.00      -1.00       -8.00 -242.00     13.00
           D         -43.00       0.00       -1.00 -169.00      4.00
           E         -18.00       0.00        5.00  -87.00      6.00
percentage A          -0.26      -0.09       -0.10   -0.30      0.09
           B          -0.21      -0.17       -0.03   -0.28      0.16
           C          -0.32      -0.09       -0.07   -0.42      0.07
           D          -0.27       0.08       -0.01   -0.36      0.03
           E          -0.15       0.09        0.05   -0.29      0.04

                  edu_other
           label
values     A         -11.00
           B          -1.00
           C           1.00
           D          -1.00
           E           1.00
percentage A          -0.28
           B          -0.05
           C           0.05
           D          -0.06
           E           0.08

In [52]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.HEALTH_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                    410   411    412    413   414   420   421   422   423  \
           label
values     A      11.00  5.00 -11.00  -1.00 -2.00 -5.00 -2.00 -2.00 -0.00
           B      -1.00 -3.00  -1.00  -8.00 -0.00  4.00  0.00  1.00 -0.00
           C      -7.00 -4.00  -4.00 -13.00 -5.00 -4.00 -1.00 -1.00 -0.00
           D     -23.00 -7.00 -10.00 -14.00 -3.00 -4.00 -1.00 -1.00  0.00
           E     -11.00 -4.00  -7.00 -11.00 -2.00 -6.00 -0.00 -1.00  0.00
percentage A       0.12  0.08  -0.18  -0.01 -0.10 -0.07 -0.27 -0.14 -0.35
           B      -0.01 -0.05  -0.02  -0.10 -0.00  0.06  0.02  0.11 -0.14
           C      -0.07 -0.08  -0.08  -0.18 -0.21 -0.07 -0.17 -0.11 -0.07
           D      -0.24 -0.15  -0.20  -0.22 -0.17 -0.07 -0.11 -0.07  0.40
           E      -0.13 -0.10  -0.18  -0.20 -0.09 -0.13 -0.06 -0.09  0.63

                   424
           label
values     A      0.00
           B     -1.00
           C     -0.00
           D     -0.00
           E     -0.00
percentage A      0.07
           B     -0.32
           C     -0.20
           D     -0.01
           E     -0.23

## Eligibility: has schoolchildren, Treatment: midday meals

In [55]:
edf = df[df['n_schoolchildren'] > 0].copy()
edf['treat'] = (edf['n_school_meals'] > 0).astype(int)

In [56]:
xdf = hces.propensity_score_match(edf, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [58]:
xdf['treat'] = xdf['treat'].astype(int)
xdf[hces.FOOD_COLS] /= xdf['family_size'].values.reshape(-1, 1)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits   meat  \
           label
values     A       -30.00  -13.00       -6.00 -196.00 -21.00  -42.00  58.00
           B       -28.00  -16.00       -5.00 -152.00 -18.00  -37.00  24.00
           C        -3.00   -7.00       -4.00  -96.00  -4.00  -18.00  22.00
           D        -2.00   -7.00       -3.00  -78.00  -3.00  -20.00  18.00
           E        -1.00   -7.00       -3.00  -67.00  -5.00  -19.00  -2.00
percentage A        -0.11   -0.14       -0.14   -0.32  -0.07   -0.24   0.30
           B        -0.11   -0.17       -0.13   -0.31  -0.07   -0.24   0.11
           C        -0.01   -0.08       -0.10   -0.23  -0.02   -0.14   0.11
           D        -0.01   -0.08       -0.08   -0.22  -0.01   -0.16   0.09
           E        -0.00   -0.09       -0.08   -0.22  -0.02   -0.17  -0.01

                   oil  spice    bev  cooked  processed
           label
values     A     -8.00 -11.00 -34.00   46.00     -45.00
           B     -9.00 -17.00 -27.00   61.00     -36.00
           C     -0.00  -7.00 -16.00  109.00     -18.00
           D     -1.00  -5.00 -14.00  125.00     -13.00
           E     -3.00  -4.00 -15.00  156.00     -11.00
percentage A     -0.06  -0.07  -0.19    0.17      -0.20
           B     -0.08  -0.11  -0.18    0.28      -0.19
           C     -0.00  -0.05  -0.14    0.75      -0.12
           D     -0.01  -0.04  -0.13    0.94      -0.10
           E     -0.03  -0.03  -0.16    1.27      -0.08

In [59]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery    fees  coaching  \
           label
values     A        -158.00      -5.00      -42.00 -383.00      7.00
           B        -136.00      -4.00      -29.00 -378.00     24.00
           C        -106.00      -2.00      -22.00 -377.00     57.00
           D        -104.00      -1.00      -23.00 -403.00     66.00
           E         -78.00      -1.00      -14.00 -308.00     61.00
percentage A          -0.56      -0.53       -0.30   -0.57      0.02
           B          -0.54      -0.55       -0.23   -0.59      0.12
           C          -0.52      -0.37       -0.20   -0.65      0.35
           D          -0.55      -0.26       -0.22   -0.71      0.56
           E          -0.50      -0.29       -0.14   -0.72      0.71

                  edu_other
           label
values     A         -20.00
           B         -20.00
           C          -9.00
           D         -12.00
           E          -7.00
percentage A          -0.47
           B          -0.55
           C          -0.40
           D          -0.50
           E          -0.41

## LPG Subsidy

In [65]:
edf = df[df['energy_source_cooking'] == 'LPG'].copy()
edf['treat'] = (edf['received_subsidy_lpg'] == 1).astype(int)

In [66]:
xdf = hces.propensity_score_match(edf, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [72]:
xdf['treat'] = xdf['treat'].astype(int)
xdf[hces.FOOD_COLS] /= xdf['family_size'].values.reshape(-1, 1)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits   meat  \
           label
values     A         4.00  -13.00       -8.00 -130.00 -20.00  -25.00  57.00
           B         9.00   -7.00       -8.00 -113.00  -3.00  -13.00  50.00
           C         4.00   -3.00       -6.00  -95.00  -5.00  -11.00  46.00
           D         6.00   -2.00       -6.00  -65.00   1.00   -1.00  30.00
           E        -4.00    2.00       -3.00  -57.00   3.00  -10.00   1.00
percentage A         0.01   -0.10       -0.18   -0.22  -0.06   -0.10   0.19
           B         0.03   -0.06       -0.18   -0.22  -0.01   -0.06   0.17
           C         0.02   -0.03       -0.14   -0.19  -0.02   -0.06   0.19
           D         0.02   -0.02       -0.13   -0.15   0.00   -0.01   0.12
           E        -0.02    0.02       -0.08   -0.11   0.01   -0.07   0.01

                    oil  spice    bev  cooked  processed
           label
values     A     -16.00 -28.00 -65.00 -138.00     -59.00
           B     -12.00 -14.00 -30.00  -73.00     -27.00
           C      -5.00 -13.00 -29.00  -42.00     -26.00
           D      -3.00  -9.00 -12.00   -8.00      -9.00
           E      -3.00 -14.00  -4.00   -2.00      -6.00
percentage A      -0.10  -0.13  -0.26   -0.30      -0.21
           B      -0.08  -0.07  -0.15   -0.21      -0.12
           C      -0.04  -0.08  -0.17   -0.16      -0.13
           D      -0.02  -0.05  -0.08   -0.04      -0.06
           E      -0.03  -0.09  -0.03   -0.01      -0.04

In [69]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery   fees  coaching  edu_other
           label
values     A          27.00      -0.00        7.00  31.00     44.00      -1.00
           B           9.00      -1.00        2.00   3.00     41.00      -4.00
           C          -4.00      -1.00        4.00 -16.00     42.00      -5.00
           D           9.00       0.00        6.00   6.00     39.00      -4.00
           E          13.00      -0.00       20.00   9.00     54.00      -5.00
percentage A           0.24      -0.04        0.13   0.10      0.46      -0.05
           B           0.08      -0.20        0.04   0.01      0.46      -0.15
           C          -0.03      -0.16        0.06  -0.05      0.44      -0.23
           D           0.08       0.07        0.10   0.02      0.63      -0.22
           E           0.09      -0.01        0.25   0.02      0.61      -0.25

## Free electricity

In [73]:
edf = df[df['energy_source_lighting'].str.startswith('electricity')].copy()
edf['treat'] = (edf['received_free_electricity'] == 1).astype(int)

In [74]:
xdf = hces.propensity_score_match(edf, num_cols=['family_size', 'n_children', 'n_elderly'],
                                  cat_cols=['sector', 'nss_region', 'employed_annual', 'max_income_from', 'hoh_religion', 'caste'])

In [76]:
xdf['treat'] = xdf['treat'].astype(int)
xdf[hces.FOOD_COLS] /= xdf['family_size'].values.reshape(-1, 1)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.FOOD_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  cereals  pulses  sugar_salt   dairy    veg  fruits    meat  \
           label
values     A         6.00    2.00        9.00  251.00   1.00    0.00 -132.00
           B       -18.00  -16.00        4.00  101.00 -49.00  -36.00 -105.00
           C        29.00   -9.00        7.00  162.00  -3.00   14.00  -35.00
           D        18.00    2.00        0.00   19.00 -32.00    9.00    3.00
           E        23.00    3.00       -3.00   22.00   4.00   20.00   29.00
percentage A         0.03    0.03        0.24    0.48   0.00    0.00   -0.50
           B        -0.07   -0.18        0.10    0.22  -0.16   -0.21   -0.43
           C         0.14   -0.10        0.20    0.41  -0.01    0.12   -0.19
           D         0.08    0.03        0.01    0.06  -0.11    0.07    0.01
           E         0.09    0.03       -0.07    0.06   0.01    0.12    0.10

                    oil  spice    bev  cooked  processed
           label
values     A      -3.00  -3.00  15.00   80.00      -3.00
           B     -27.00 -17.00  -1.00   17.00     -31.00
           C     -10.00  17.00  39.00  116.00       8.00
           D     -15.00   6.00  20.00   55.00       2.00
           E     -17.00   8.00  39.00   80.00      23.00
percentage A      -0.02  -0.02   0.09    0.33      -0.01
           B      -0.20  -0.10  -0.01    0.06      -0.15
           C      -0.08   0.12   0.37    0.65       0.06
           D      -0.11   0.04   0.18    0.26       0.01
           E      -0.13   0.05   0.25    0.23       0.14

In [78]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.EDU_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                  books_1st  books_2nd  stationery   fees  coaching  edu_other
           label
values     A         -17.00       0.00       17.00   5.00    -63.00       4.00
           B         -21.00       0.00       10.00   3.00    -91.00       1.00
           C         -23.00       1.00        9.00   9.00    -74.00       5.00
           D           7.00       1.00        9.00  51.00    -61.00       2.00
           E          17.00       2.00        9.00  63.00    -20.00       8.00
percentage A          -0.12       0.05        0.24   0.01     -0.40       0.17
           B          -0.18       0.05        0.15   0.01     -0.56       0.05
           C          -0.21       0.18        0.15   0.03     -0.60       0.39
           D           0.10       0.23        0.17   0.26     -0.53       0.21
           E           0.21       0.81        0.17   0.28     -0.45       0.57

In [79]:
xdf['treat'] = xdf['treat'].astype(int)
ydf = hces.compare(xdf[xdf['support']], ['label', 'treat'], hces.HEALTH_COLS)
vals = ydf.xs(1, level='treat') - ydf.xs(0, level='treat')
pc = vals / ydf.xs(0, level='treat')
pd.concat([vals.round(), pc.round(2)], axis=0, keys=['values', 'percentage'])

                    410   411    412    413   414    420   421   422   423  \
           label
values     A     -15.00  2.00 -10.00  -6.00  4.00  -2.00 -0.00 -1.00 -0.00
           B      -9.00 -8.00 -13.00 -15.00  3.00 -11.00 -1.00 -2.00  0.00
           C     -14.00 -1.00  -8.00 -15.00  2.00  -1.00  1.00  0.00 -0.00
           D      19.00  6.00   9.00   8.00  1.00  -5.00 -1.00  1.00 -0.00
           E      10.00  3.00  15.00   8.00  4.00  -2.00 -0.00  2.00  0.00
percentage A      -0.16  0.04  -0.23  -0.10  0.19  -0.03 -0.02 -0.14 -0.26
           B      -0.09 -0.16  -0.23  -0.21  0.15  -0.17 -0.11 -0.21  0.11
           C      -0.15 -0.03  -0.18  -0.24  0.13  -0.02  0.15  0.03 -0.25
           D       0.27  0.14   0.23   0.15  0.04  -0.10 -0.14  0.11 -0.04
           E       0.10  0.05   0.25   0.11  0.22  -0.03 -0.02  0.20  0.06

                   424
           label
values     A     -1.00
           B     -0.00
           C      0.00
           D     -0.00
           E     -0.00
percentage A     -0.29
           B     -0.09
           C      0.06
           D     -0.28
           E     -0.23